# Feature Engineering

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("Datasets/WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [3]:
data.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [4]:
drop_cols = ['EmployeeCount','StandardHours','EmployeeNumber','Over18']

data_cleaned = data.drop(columns=drop_cols)

In [5]:
data_cleaned.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,4,1,6,3,3,2,2,2,2

In [6]:
data_cleaned['AgeGroup'] = pd.cut(data_cleaned['Age'],bins=[18,25,35,45,60],labels=['18-25','26-35','36-45','46-60'])

In [7]:
pd.crosstab(data_cleaned['AgeGroup'],data_cleaned['Attrition'],normalize='index')*100

Attrition         No        Yes
AgeGroup
18-25      65.217391  34.782609
26-35      80.858086  19.141914
36-45      90.811966   9.188034
46-60      87.545788  12.454212

In [8]:
data_cleaned['IncomeGroup'] = pd.qcut(data_cleaned['MonthlyIncome'],q=4)

In [9]:
pd.crosstab(data_cleaned['IncomeGroup'],data_cleaned['Attrition'],normalize='index')*100

Attrition                  No        Yes
IncomeGroup
(1008.999, 2911.0]  70.731707  29.268293
(2911.0, 4919.0]    85.792350  14.207650
(4919.0, 8379.0]    89.373297  10.626703
(8379.0, 19999.0]   89.673913  10.326087

In [10]:
pd.crosstab(data_cleaned['OverTime'],data_cleaned['JobRole'],values=(data_cleaned['Attrition'] == 'Yes'),aggfunc='mean')*100

JobRole,Healthcare Representative,Human Resources,Laboratory Technician,Manager,Manufacturing Director,Research Director,Research Scientist,Sales Executive,Sales Representative
OverTime,,,,,,,,,
No,7.446809,17.948718,15.736041,1.333333,5.660377,1.754386,7.179487,11.206897,28.813559
Yes,5.405405,38.461538,50.000000,14.814815,10.256410,4.347826,34.020619,32.978723,66.666667

In [11]:
data_cleaned['IsYoungEmployee'] = np.where(data_cleaned['Age'] < 30,1,0)

In [12]:
data_cleaned['LowIncome'] = np.where(data_cleaned['MonthlyIncome'] < data_cleaned['MonthlyIncome'].median(),1,0)

In [13]:
income_median = data_cleaned['MonthlyIncome'].median()

print(income_median)

4919.0

In [14]:
data_cleaned['LongDistance'] = np.where(data_cleaned['DistanceFromHome'] > 10,1,0)

In [15]:
data_cleaned['PromotionDelay'] = np.where(data_cleaned['YearsSinceLastPromotion'] >= 5,1,0)

In [16]:
data_cleaned['HighRiskOvertime'] = np.where((data_cleaned['OverTime'] == 'Yes') &
(data_cleaned['JobRole'].isin(['Sales Representative','Laboratory Technician','Human Resources'])),1,0)

In [17]:
data_cleaned.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,AgeGroup,IncomeGroup,IsYoungEmployee,LowIncome,LongDistance,PromotionDelay,HighRiskOvertime
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,4,0,5,36-45,"(4919.0, 8379.0]",0,0,0,0,0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,7,1,7,46-60,"(4919.0, 8379.0]",0,0,0,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,0,0,0,36-45,"(1008.999, 2911.0]",0,1,0,0,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,7,3,0,26-35,"(1008.999, 2911.0]",0,1,0,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,2,2,2,26-35,"(2911.0, 4919.0]",1,1,0,0,0

In [18]:
cols_to_drop = ['AgeGroup','IncomeGroup']

data_cleaned.drop(columns=cols_to_drop,inplace=True)
data_cleaned.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,...,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,IsYoungEmployee,LowIncome,LongDistance,PromotionDelay,HighRiskOvertime
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,2,Female,...,1,6,4,0,5,0,0,0,0,0
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,3,Male,...,3,10,7,1,7,0,0,0,0,0
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,4,Male,...,3,0,0,0,0,0,1,0,0,1
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,4,Female,...,3,8,7,3,0,0,1,0,0,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,Male,...,3,2,2,2,2,1,1,0,0,0

In [19]:
data_cleaned.to_csv("Datasets/processed_hr_data.csv",index=False)

In [20]:
data_encoded = pd.get_dummies(data_cleaned,drop_first=True,dtype=int)

In [21]:
data_encoded.shape

(1470, 50)

In [22]:
data_encoded.to_csv("Datasets/processed_hr_data_model.csv",index=False)